function [R1,R2,X_,Y_] = ExpFitting(X,Y)
    L_Y = length(Y);
    L_X = length(X);
    c2m = cell2mat(Y);
    index = find(isnan(c2m));
    Y(index) = [];
    X(index) = [];
    y = cell2mat(Y);
    x = cell2mat(X);
    fo = fitoptions('Normalize', 'off',...
           'Method', 'NonlinearLeastSquares',...
           'Robust', 'Off',...
       'StartPoint', [1,1],...
        'Algorithm', 'Trust-Region',...
    'DiffMinChange', 1.0000e-08,...
    'DiffMaxChange', 0.1000,...
      'MaxFunEvals', 600,...
          'MaxIter', 400,...
           'TolFun', 1.0000e-06,...
             'TolX', 1.0000e-06);
    [R1,R2] = fit(x,y,'exp1', fo);
    X_ = x;
    Y_ = R1.a*exp(R1.b*x);
end
